[programs.localnet]
phhdao = "74UV6yKRkHzzkATgrGzPTUhhML6u48ST1BHxjUiScg52"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/nagy/Desktop/HackerHouse/decidooor/secret/phhdao.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.tsx"
